name: Go

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Install dependencies
      run: go mod tidy

    - name: Build Windows GUI executable
      run: GOOS=windows GOARCH=amd64 go build -ldflags "-H windowsgui" -o wlzntfy-go.exe

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} wlzntfy-go.exe
