name: Go

on:
  release:
    types: [created, edited]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Install dependencies
      run: go mod tidy

    - name: Build Windows GUI executable
      run: GOOS=windows GOARCH=amd64 go build -ldflags "-H windowsgui" -o wlzntfy-go.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: wlzntfy-go
        path: wlzntfy-go.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: wlzntfy-go

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.event.release.tag_name }}
        release_name: ${{ github.event.release.name }}
        body: ${{ github.event.release.body }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./wlzntfy-go.exe
        asset_name: wlzntfy-go.exe
        asset_content_type: application/octet-stream
